# Generated by Django 4.2 on 2023-05-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogpost_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='catch_phrase',
            field=models.TextField(default='Bla Bla'),
        ),
    ]
